lib/espec/assertion_helpers.ex, lib/espec/assertions/be_type.ex, spec/assertions/be_type_spec.exs
Allows checking whether a term is a struct, and optionally that it is a
specific type of struct:
```elixir
defmodule StructExample do
defstruct a: 1, b: 2
end
defmodule StructExampleSpec do
use ESpec
subject %StructExample{}
it do: is_expected.to be_struct
it do: is_expected.to be_struct(StructExample)
end
```
=> Add `be_struct` matcher.

lib/mix/tasks/init.ex
* Use two spaces instead of a tab
* Remove whitespace at the end of lines
=> Clean up whitespace in templates created by the 'init' Mix task

lib/espec/runner.ex
Previously, ESpec would crash when running recursively, as in the case
of an umbrella project because `:seed` would be stored as an integer,
then have `String.to_integer` called on it.
This handles `:seed` being `nil`, an integer, or a string.
=> Handle `Configuration.get(:seed)` being integer

lib/mix/tasks/init.ex, test/mix/espec_init_test.exs
I added an option to espec.init task, to skip creation of examples.
If it is ok, I will make it for espec_phoenix as well.
=> Add --skip-examples option for espec.init

lib/espec.ex, lib/espec/example_runner.ex, lib/espec/let.ex, spec/let_spec.exs
This rework of the `let` implementation should fix #84 . It passes that test case (easily, since there is no longer any use of `Code.eval_quoted`) and does not break any existing test.
Technical details are in the commit logs. I hope this patch is useful, please let me know if anything needs improvement.
=> Fix let (#84)

lib/espec/example.ex, lib/espec/example_runner.ex, lib/espec/let.ex, spec/let_spec.exs
This restores `let!` functionality (evaluate block in a `before` block) and adds a test for it. See the commit log for the gory details. Sorry again for breaking it. Hopefully this does not add more breakage, but having been burned once, I can't say I'm entirely confident.
I'm not really happy with how the shared state is now "magically" passed to those `let` blocks. We now have complicated code to basically simulate mutable variables in Elixir :worried:
I don't have a better idea however for making complicated cases like #82 work as expected, while handling the various possible interactions of shared state and lazily evaluated functions…
=> Make let! work again (fix #86)

README.md
=> Fix custom_assertion_spec.exs link in README

lib/espec/doc_example.ex, test/docs/doc_test_test.exs
When trying to include moduledocs as part of doctests using ESpec, it would return this error
```
** (MatchError) no match of right hand side value: nil
spec/forte/duration_spec.exs:4: anonymous fn/2 in :elixir_compiler_6.__MODULE__/1
(elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
spec/forte/duration_spec.exs:4: (module)
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```
The problem was that `fun_arity` was being set to `nil` for tests extracted from moduledocs, rather than the `{:fun_name, arity}` tuple that was expected.
This PR sets `fun_arity` for tests extracted from moduledocs to `{:moduledoc, 0}`, so that they can be correctly tested by ESpec, and can also be passed to the `only:` and `except:` options for the `moduledoc` macro.
=> Adds a fun_arity for tests found in moduledocs.

README.md, lib/espec/assertion_helpers.ex, lib/espec/assertions/enum/be_empty.ex, lib/espec/assertions/string/be_blank.ex, spec/assertions/enum/be_empty_spec.exs, spec/assertions/string/be_blank_spec.exs, test/assertions/string/be_blank_test.exs
* Adds `be_blank`
* Extends `be_empty` to check against strings as well as collections
References https://github.com/antonmi/espec/issues/126
=> Add blank/empty assertions for strings

lib/espec/runner.ex
OTP 19.0
```
warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
lib/espec/runner.ex:201
```
http://erlang.org/doc/man/rand.html
=> Use :rand instead of :random which is deprecated

README.md, lib/espec/assertion_helpers.ex, lib/espec/assertions/binary/have_byte_size.ex, spec/assertions/binary/have_byte_size_spec.exs, test/assertions/binary/have_byte_size_test.exs
This uses `byte_size(binary)` to test the actual byte size of the binary (as opposed to `String.length` which tests for the UTF-8-encoded character count).
=> Implement have_byte_size

lib/espec/support.ex, mix.lock, test/examples/example_test.exs, test/support_test.exs
Hello. I've noticed that ESpec crashes when you use non-ascii characters in the example name, so here's my proposed solution with some tests.
=> Added support for unicode in example names

lib/espec/example_runner.ex
This fixes warning in Elixir 1.3.4.
=> Remove obsolete variable usage in ExampleRunner

lib/espec/allow_to.ex
Hint about this function was given by `credo`.
The downside of the new approach is too big length of some lines. But from the compexity standpoint it's better.
=> Rewrite complex ESpec.AllowTo#to/2 to pattern matching

mix.exs, mix.lock
On the current `master` credo didn't work for me: it failed with an error:
```
Compiling 120 files (.ex)
warning: variable new_issues is unused
lib/credo/check/consistency/helper.ex:118
warning: variable line is unused
lib/credo/cli/output/explain.ex:130
warning: function Hex.Utils.ensure_registry!/0 is undefined or private
lib/credo/check_for_updates.ex:4
warning: function Hex.Registry.get_versions/1 is undefined or private
lib/credo/check_for_updates.ex:9
Generated credo app
** (UndefinedFunctionError) function Hex.Utils.ensure_registry!/0 is undefined or private
(hex) Hex.Utils.ensure_registry!()
lib/credo/check_for_updates.ex:4: Credo.CheckForUpdates.run/0
lib/credo/cli.ex:92: Credo.CLI.run/1
lib/credo/cli.ex:58: Credo.CLI.main/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) …
```
=> Bump credo version

lib/espec/runner.ex
A warning was added in the Elixir 1.4.0 version when the default implementation of GenServer handle_info is used _([GenServer] Log warn on default handle_info/2 implementation)_. I simply added some lines to remove this warning.
=> Add default handle_info implementation for runner.ex

lib/espec/assertions/refute_receive.ex, lib/espec/expect_to.ex, lib/espec/output/doc.ex
Elixir 1.4 introduced some new warnings - including the one with unused module attributes.
This PR removes module attributes which caused warnings.
Also, I haven't touched few of those, as they're used by `credo`:
```
warning: module attribute @lint was set but never used
lib/espec/doc_example.ex:214
warning: module attribute @lint was set but never used
lib/espec/doc_test.ex:49
```
=> Remove unused module attributes

spec/assertions/change_spec.exs, test/assertions/change_test.exs
Elixir 1.4 introduced some new warnings, which were being triggered in `espec`.
This PR fixes the following warnings:
```
warning: Set.put/2 is deprecated, use the MapSet module for working with sets
spec/assertions/change_spec.exs:4
warning: Set.to_list/1 is deprecated, use the MapSet module for working with sets
spec/assertions/change_spec.exs:5
warning: Set.put/2 is deprecated, use the MapSet module for working with sets
test/assertions/change_test.exs:7
warning: Set.to_list/1 is deprecated, use the MapSet module for working with sets
test/assertions/change_test.exs:8
```
=> Remove usages of deprecated Set module

lib/espec/suite_runner.ex
Current implementation of get_closest when running specs with line parameter yields unexpected results.
if I have
and try to run the spec with line `:8` it will actually run the spec on line 10, which is highly unintuitive. I would expect it to run the spec in which the line is in.
In order to do this, I propose this simple heuristic: Always run the previous spec. If there is none, run the first one
What do you think?
=> running suite by line runs the test the line is in

lib/espec/assertions/eq.ex, lib/espec/formatters/doc.ex, lib/espec/formatters/html.ex, lib/espec/struct_diff.ex, spec/assertions/eq_spec.exs, spec/struct_diff_spec.exs, test/docs/doc_test_test.exs, test/example_runner_test.exs, test/output/doc_test.exs
When an eq-assertions fails for a deep structure, the differences can be hard to spot.
The proposed changes adds a rudimentary diff-spec, that identifies changes and tries to express them more concisely. Can certainly be improved, but it's a start
=> Diff Structures for complex eq errors

README.md, lib/espec/example_helpers.ex, spec/generated_examples_spec.exs, test/generated_examples_test.exs
I added a new feature you might like (I felt a need for it when DRY-ing my tests).
Examples can be generated via loops:
```elixir
subject 1..5
Enum.map 1..3, fn(n) ->
it do: is_expected().to have(unquote(n))
end
```
And examples descriptions can contain interpolations:
```elixir
subject(24)
Enum.map 2..4, fn(n) ->
it "is divisible by #{n}" do
expect(rem(subject(), unquote(n))).to be(0)
end
end
```
I think the above is better than:
```elixir
subject(24)
it "is divisible by some numbers" do
Enum.map 2..4, fn(n) ->
expect(rem(subject(), n)).to be(0)
end
end
```
Better because one can see all the tests that fail at once rather than just the first. And the only change to the code inside the test is that ```unquote``` call (which should not affect the readability that much).
=> Allowed generated examples

lib/espec/diff.ex, test/output/doc_diff_test.exs
Same as in `ExUnit`, I added a time limit for formatting the actual diff (and the diff itself is ran in another process).
I should have done this from the beginning. Without this, when the diff arguments are long strings, I get a `GenServer` timeout when the `stop` function for the `Doc` formatter is called (as the formatter has not yet finished doing the diff).
=> Added a 1.5 seconds time limit for doing the diff

lib/espec/configuration.ex, lib/espec/output.ex
The timeout for the formatters to do their job can be configured like this:
```elixir
ESpec.configure fn(config) ->
config.formatters_timeout 30_000
end
```
Should only be needed when there are a lot of failed test cases with `eq`-like assertions on long collections or strings (and, of course, the Doc formatter is active).
A message will be displayed (with the above as a suggestion) when the `ESpec.Output` process `stop` call times out.
=> Made the output formatters configurable (via config.formatters_timeout)

.travis.yml, lib/espec.ex
As discussed in issue "compability with Elixir 1.5" i have added a version to check inside a macro so we can call ExUnit.CaptureServer.start_link with the proper arity.
I have tested it with Elixir 1.5.0 and 1.4.1 and `mix espec` worked fine. On `mix test` however there seems to be another issue regarding Elixir 1.5.0.
=> Elixir 1.5 compatibility for ExUnit.CaptureServer

lib/espec/assert.ex, lib/espec/assert_receive.ex, lib/espec/assertion_error.ex, lib/espec/assertions/contain_exactly.ex, lib/espec/assertions/interface.ex, lib/espec/diff.ex, lib/espec/expect.ex, lib/espec/expect_to.ex, lib/espec/formatters/doc.ex, lib/espec/refute_receive.ex, lib/espec/should.ex, lib/espec/to.ex, spec/diff_spec.exs, spec_formatters/diff_showcase_spec.exs, test/output/doc_diff_test.exs, test/output/doc_stacktrace_test.exs, test/output/example_spec_dot.exs, test/output/example_spec_pipe.exs, test/output/example_spec_should.exs
Hi @antonmi,
I added the stacktrace to the failed examples. And made a change to the way the diff is displayed for the `contains_exactly` assertion (gave up aligned diff, wasn't useful most of the times and sometimes it looked quite bad).
Here is an example of how the stacktrace is displayed:
Please have a look at the code and if you think it is useful merge it.
Thanks!
=> Added the stacktrace to the failed examples

lib/mix/tasks/espec.ex
Relating to: https://github.com/antonmi/espec/issues/221
By taking out the `parse!` we don't raise when mix options are passed in, but by retaining the strict check, we filter out any non-espec options from `opts`
We can then safely check for `--(no)-compile` in mix_opts
However, for line 120 (`Mix.Task.run "app.start", args`) we don't want to do the same sort of check, as we should delegate the decision as to how much to "start" to Mix. This lets it do things like use the configuration for things like logging (e.g. config/test.exs) while not starting up the main application process
I also did not want to specifically whitelist Mix arguments in here, as that might get out of date with subsequent releases of Mix
=> Re-enable passing of Mix options through

lib/espec/let/let.ex, spec/let/let_spec.exs
Instead of passing the keyword list directly to before, we now generate a list of calls to the generated functions.
Using `let! a: 1, b: 2` results in:
```elixir
let a: 1, b: 2
before a: 1, b: 2
```
Using `let! a: 1, b: 2` results in:
```elixir
let a: 1, b: 2
before do
[a(), b()]
end
```
This ensures that the values of the keyword list really only get evaluated once, which is important when these values affect the global state.
=> Ensure that `let!` with a keyword list only evaluates once for each example

README.md
As discussed in #225 this pull request adds a section detailing how to use shared examples which are in separate files.
=> README: Explain how to ensure compilation of shared examples in seperate files

README.md, lib/espec/doc_test.ex, spec/doc_test_spec.exs
This is an improvement on the first version using sigils with delimiters which again requires to escape `'` characters.
The changes in this PR will allow __all__ characters to appear in an exception message. This is achieved by rendering the exception message as a binary instead of a string.
=> DocTests: Improve exception message handling

README.md, lib/espec/assertion_helpers.ex, lib/espec/assertions/match_pattern.ex, spec/assertions/match_pattern_spec.exs, test/assertions/match_pattern_test.exs
As discussed in #232 this PR implements a new matcher called `MatchPattern` and can be used like this:
```elixir
expect actual |> to(match_pattern {:ok, _})
```
---
It is possible to use `^pinned_variables` but not to call functions in the match, which is consistent with elixirs match behaviour.
---
The README was updated with a new `Pattern` section.
=> Feature - Implement `match_pattern` assertion

lib/espec/assertions/match_pattern.ex, test/assertions/match_pattern_test.exs
This PR improves the added `MatchPattern` assertion by ensuring that all subjects work fine with the assertion. Some values can not be represented in an quote and need to be *escaped* (using `Macro.escape/1`).
The subject now always get's escaped which allows all kind of values in the matcher.
---
Furthermore this PR greatly simplifies the actual match generation by making use of the 2nd and 3rd parameter of the `Code.eval_quoted`. Which allow to define bindings and all environment specific values.
This in turn improves the error message when using functions in a match. Before this the error would've complained that the function is not available, especially if the function was defined with a `let`. Now the compiler actually complains about a function used in a match.
=> Assertion - MatchPattern: Improve map handling and function usage error message

lib/espec/assertions/raise_exception.ex, spec/assertions/raise_exception_spec.exs
When expecting an exception and an unexpected exception is raised, ESpec would incorrectly report that nothing had been raised. This improves the error message in the case of not expecting a specific exception message and creates a spec for when a specific exception message is expected.
=> Improve the error message when an unexpected exception is raised

README.md, lib/espec/assertions/enum_string/have.ex, spec/assertions/map/have_spec.exs, test/assertions/map/have_test.exs
This PR adds `match` clauses to for Maps and Structs to allow for expectations like this:
```elixir
expect(%{}).to_not have(foo: "bar")
```
As you can see it also adds a special case to handle single element Keyword lists which makes testing for key value pairs a breeze.
=> Assertions: Add match clauses to use `have` for Maps and Structs

.formatter.exs
As discussed in #252 
The `locals_without_parens` list is probably not 100% complete, but I formatted the ESpec codebase locally and it looks like a good starting point that we can expand iteratively.
Did not format the codebase in this PR because it significantly bloats the diff.
To format, you can just run `mix format` on `v1.6.0-rc.0` or `master` Elixir.
`expect(...).to` and `should` syntax looks different, not sure if it's feasible to make it look the exact as it currently does with the formatter applied.
As usual, feel free to apply any changes you see fit @antonmi 
Best,
Jan
=> Mix formatter configuration

test/configuration/config_finally_error_test.exs
When raising or throwing something in config.finally the test succeeds and swallows the error silently which can lead to an undefined state and results in subsequent test failures if the config.finally block does some critical cleanup.
This PR adds two tests which currently fail due to this behaviour. It can be used to start working on a solution.
=> Test - Config.finally: Add a test which raises and throws in finally

lib/espec/assertions/enum_string/have.ex, spec/assertions/eq_spec.exs, spec/assertions/map/have_spec.exs, spec/shared/check_error_shared_spec.exs
As the title suggests. The error message for the `enum_string/have.ex` assertions has been extended.
It now actually talks about keys and values. It also returns a `diff_fn` for a positive match with the expected and actual data.
```
Expected `[a: 1]` to have `{:a, 2}`, but it has not.
```
```
Expected `[a: 1]` to have `2` for key `:a`, but it has not.
expected: 1
actual:   2
```
---
In addition it extends the `CheckErrorSharedSpec` to allow checking for an `extra` in the raised error. This is used to test the inclusion of the diff in the `have` assertion and also for `eq` whose spec has been extended.
=> Feature: Add a diff for the `have` spec when it looks for a key-value tuple

.formatter.exs
This PR allows a couple more macros to be formatted without parens
=> Add a few missing formatting rules

lib/espec.ex, lib/espec/example_runner.ex, lib/espec/runner.ex
Fixes #283, where the whole suite might crash on a single test
=> Start every test in a new process, watch for it's death

lib/espec/assertions/interface.ex
Just happened to notice this as I was going through the code.
=> Fix small typo in documentation for Assertions.Interface

mix.exs, mix.lock
I ran into this issue detailed here: https://github.com/eproxus/meck/issues/201
This was due to the Meck dependency being locked on `0.8.12`. In order to fix this, I included an override in my `mix.exs` file. This PR should make having to add the override unnecessary and let meck freely upgrade to capture fixes like these.
Thanks :)
=> Bump version of Meck dependency to include fix for Elixir 1.8.x

lib/espec/example.ex, lib/espec/example_runner.ex, spec/regression/incorrect_shared_values_in_before_spec.exs, test/examples/example_extract_option_test.exs
This PR fixes an issue with the tags passed into `before` blocks. The issue occurred when a tag was overwritten in a lower context and then the same tag accessed in the `before` clause.
See the below added and currently failing regression test:
```elixir
defmodule Regression.IncorrectSharedValuesInBeforeSpec do
use ESpec, option: true
before do: send self(), {:option, shared[:option]}
it "option should be true" do
assert_receive {:option, true}
end
it "option should be false", option: false do
assert_receive {:option, false}
end
end
```
The cause for this issue was that `Example.extract_options/1` returned a Keyword list with all entries, sorted by most specific to least specific.
https://github.com/antonmi/espec/blob/541ca38e9b548cbcc5c23882ee4af97c21f17b3c/lib/espec/example.ex#L72-L75 …
=> Bugfix - Incorrect shared values in before

lib/espec/doc_test.ex
For a doctest that uses an `:inspect` a warning is issued for `elixir 1.8.2-otp-22`
```
warning: parentheses are required when piping into a function call. For example:
foo 1 |> bar 2 |> baz 3
is ambiguous and should be written as
foo(1) |> bar(2) |> baz(3)
```
=> Add parenthesis to avoid ambiguous pipe in doctest

.gitignore, lib/espec/assertions/accepted.ex, spec/assertions/accepted_spec.exs
Error messages for failed 'accepted` assertions now contain a phrase
such as "The function was called with arguments [:a, :b]".
Addresses https://github.com/antonmi/espec/issues/242
=> Make 'accepted' assertion messages more descriptive

README.md
I noticed that some type check matchers  are missing in README, so I added them.
I decided what to add based on the type spec file ,`be_type_spec.exs`.
https://github.com/antonmi/espec/blob/ba6a4cc8106814f9187e88cf96596a77d59ca539/spec/assertions/be_type_spec.exs
=> Add missing type checking matcher to README

lib/mix/tasks/espec.ex
Currently, `mix espec` command return zero exit code in case when there is some error during spec files compilation step:
```
bash-5.0$ mix espec
Compiling 1 file (.ex)
==> arkenston
== Compilation error in file spec/arkenston/mutator/user_mutator_spec.ex ==
** (SyntaxError) spec/arkenston/mutator/user_mutator_spec.ex:67: unexpected token: ). The "do" at line 60 is missing terminator "end"
(elixir 1.10.3) lib/kernel/parallel_compiler.ex:305: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
0 examples, 0 failures
Finished in 0.37 seconds (0.36s on load, 0.0s on specs)
Randomized with seed 22698
bash-5.0$ echo $?
0
```
This is very annoying because CI/CD process does not known that testing step was failed.
The only way to detect such a failure is to check coverage percentage which …
=> Fail if spec files cannot be compiled

lib/espec/suite_runner.ex, lib/mix/tasks/espec.ex
This PR fixes the following warnings that seem to have been introduced in one of the newer versions of Elixir:
```
warning: using map.field notation (without parentheses) to invoke function Mix.Shell.IO.print_app() is deprecated, you must add parentheses instead: remote.function()
(espec 1.9.2) lib/mix/tasks/espec.ex:133: Mix.Tasks.Espec.run/1
(mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
(mix 1.17.3) lib/mix/task.ex:561: Mix.Task.run_alias/6
(mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
warning: using map.field notation (without parentheses) to invoke function Firmware.Spec.examples() is deprecated, you must add parentheses instead: remote.function()
(espec 1.9.2) lib/espec/suite_runner.ex:21: ESpec.SuiteRunner.run_module_examples/3
(espec 1.9.2) …
```
=> Fix map.field notation warnings
